<a href="https://colab.research.google.com/github/progammer24052025-png/Python-Codes/blob/main/Array_in_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import array as ar
a= ar.array('i',[1,2,3])
print(a[1])

2


In [ ]:
# Creating an array
import array as arr
a = arr.array('d', [1.1, 2.1, 3.1])  # 'd' is type code for double/float

# Accessing array elements
print(a[1])

# Finding length of array
print(len(a))

# Adding elements
a.append(3.4)  # Adds to end
print(a)

a.extend([4.5, 6.3, 6.8])  # Adds multiple elements
print(a)

a.insert(2, 3.8)  # Insert at specific position
print(a)

# Array concatenation
b = arr.array('d', [3.7, 8.6])
c = a + b
print(c)

# Removing elements
print(a.pop())
print(a.pop(3))

a.remove(1.1)  # Removes first occurrence of 1.1
print(a)

# Slicing array
print(a[0:3])

# Looping through array
print("All values")
for x in a:
    print(x)

print("Specific values")
for x in a[1:3]:
    print(x)

2.1
3
array('d', [1.1, 2.1, 3.1, 3.4])
array('d', [1.1, 2.1, 3.1, 3.4, 4.5, 6.3, 6.8])
array('d', [1.1, 2.1, 3.8, 3.1, 3.4, 4.5, 6.3, 6.8])
array('d', [1.1, 2.1, 3.8, 3.1, 3.4, 4.5, 6.3, 6.8, 3.7, 8.6])
6.8
3.1
array('d', [2.1, 3.8, 3.4, 4.5, 6.3])
array('d', [2.1, 3.8, 3.4])
All values
2.1
3.8
3.4
4.5
6.3
Specific values
3.8
3.4


In [ ]:
import numpy as np

import time
import sys
S= range(1000)
print(sys.getsizeof(5)*len(S))

D= np.arange(1000)
print(D.size*D.itemsize)

28000
8000


In [ ]:
import time

SIZE = 1000000

L1= range(SIZE)
L2= range(SIZE)
A1= np.arange(SIZE)
A2=np.arange(SIZE)

start= time.time()
result=[(x,y) for x,y in zip(L1,L2)]
print((time.time()-start)*1000)

start=time.time()
result= A1+A2
print((time.time()-start)*1000)

176.00774765014648
49.26347732543945


In [ ]:
import numpy as np
a= np.array( [1.0,2.0,4.0])
print(a[0])

1.0


In [ ]:
b = np.array([(1, 2, 3), (4, 5,9),(11, 12, 13)])
print(b)

[[ 1  2  3]
 [ 4  5  9]
 [11 12 13]]


In [ ]:
import numpy as np

# np.zeros()
zeros_arr = np.zeros((2,3))
print("zeros:\n", zeros_arr)

# np.ones()
ones_arr = np.ones((3,2))
print("\nones:\n", ones_arr)

# np.arange()
range_arr = np.arange(0, 10, 2)
print("\narange:\n", range_arr)

# np.linspace()
linspace_arr = np.linspace(0, 1, 5)
print("\nlinspace:\n", linspace_arr)

# np.random.rand()
rand_arr = np.random.rand(2,2)
print("\nrandom:\n", rand_arr)

zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

arange:
 [0 2 4 6 8]

linspace:
 [0.   0.25 0.5  0.75 1.  ]

random:
 [[0.31070958 0.13800139]
 [0.10903017 0.37529556]]


In [ ]:
import numpy as np

# Create sample arrays
a = np.array([1, 2, 3])  # 1D array
b = np.array([(1, 2, 3), (4, 5, 6)])  # 2D array

# Array properties
print("Array a:", a)
print("Array b:\n", b)

print("\nProperties of array a:")
print("ndim (number of dimensions):", a.ndim)
print("shape (dimensions):", a.shape)
print("size (total elements):", a.size)
print("dtype (data type):", a.dtype)
print("itemsize (bytes per element):", a.itemsize)

print("\nProperties of array b:")
print("ndim (number of dimensions):", b.ndim)
print("shape (dimensions):", b.shape)
print("size (total elements):", b.size)
print("dtype (data type):", b.dtype)
print("itemsize (bytes per element):", b.itemsize)

Array a: [1 2 3]
Array b:
 [[1 2 3]
 [4 5 6]]

Properties of array a:
ndim (number of dimensions): 1
shape (dimensions): (3,)
size (total elements): 3
dtype (data type): int64
itemsize (bytes per element): 8

Properties of array b:
ndim (number of dimensions): 2
shape (dimensions): (2, 3)
size (total elements): 6
dtype (data type): int64
itemsize (bytes per element): 8


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a * b)
print(np.dot(a, b))

[5 7 9]
[ 4 10 18]
32


In [ ]:
a = np.array([1, 2, 3, 7, 89, 101])

print(a.sum())
print(a.min())
print(a.max())
print(a.mean())
print(np.median(a))

203
1
101
33.833333333333336
5.0


In [ ]:
import numpy as np
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
a = a.reshape(6, 1)  # Converts to 3x2 matrix
print(a)

[[1 2 3]
 [4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [ ]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(arr[2:5])
print(arr[:5])
print(arr[5:])
print(arr[::2])
print(arr[::-1])
print(arr[-3:])
print(arr[:-3:2])




[2 3 4]
[0 1 2 3 4]
[5 6 7 8 9]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]
[7 8 9]
[0 2 4 6]


In [ ]:
arr_2d = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])

# Get first row
print(arr_2d[0, :])

# Get second column
print(arr_2d[:, 1])

# Submatrix (rows 1-2, columns 1-2)
print(arr_2d[1:3, 1:3])


# Every other row
print(arr_2d[::2, ::2])


[1 2 3]
[2 5 8]
[[5 6]
 [8 9]]
[[1 3]
 [7 9]]
