<a href="https://colab.research.google.com/github/progammer24052025-png/Python-Codes/blob/main/string_in_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#array using numpy

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
a = np.array([1.1, 2.3, 3.6])
print(a)

[1.1 2.3 3.6]


In [ ]:
arr_2d = np.array([(1, 2,3), (4, 5, 6), (7,8,9)])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
a = np.array([(1, 2, 3), (4, 5, 6)])
a = a.reshape(5, 5)  # Converts to 3x2 matrix
print(a)

ValueError: cannot reshape array of size 6 into shape (5,5)

In [ ]:
b=np.random.rand(5,5)
print(b)

[[0.11794745 0.79819434 0.44581808 0.83952927 0.8429861 ]
 [0.27683783 0.85732952 0.83198046 0.48183574 0.10047488]
 [0.49195865 0.6534401  0.19552216 0.79574797 0.11420093]
 [0.72132225 0.69646067 0.35148968 0.24356113 0.72913797]
 [0.22924664 0.77342551 0.7168478  0.33781892 0.62381967]]


In [ ]:
c=np.linspace(0, 2, 4)
print(c)

[0.         0.66666667 1.33333333 2.        ]


In [ ]:
str1 = 'Hello, World!'
str2 = "Python Programming"
str3 = '''This is a
multi-line string'''
print(str3)

This is a
multi-line string


In [ ]:
name = "Alice"
message = 'Welcome to Python'
multiline = """This is a
multi-line string."""
num_str = str(100)  # Converts integer to string
type(num_str)

str

In [ ]:
text = "hello"
#text[0] = 'H'

new_text = "H" + text[1:]  # Creates a new string "Hello"
print(new_text)  # Output: Hello

Hello


In [ ]:
str1 = "Hello"
str2 = "World"
result = str1 + " " + str2  # "Hello World"
print(result)

Hello World


In [ ]:
word = "Hi"
repeated = word * 3  # "HiHiHi"
print(repeated)

HiHiHi


In [ ]:
text = "Python"
print(text[0])   # 'P' (First character)
print(text[-6])  # 'h' (Last character)

P
P


In [ ]:
text = "Python Programming"
#(start:stop(n-1):step)
print(text[0:5:2])    # 'Python' (from index 0 to 5)
print(text[9:])     # 'Programming' (from index 7 to end)
print(text[:6])     # 'Python' (from start to index 5)
print(text[::2])    # 'Pto rgamn' (every 2nd character)
print(text[7:3:-1])   # 'gnimmargorP nohtyP' (reverse string)

Pto
ogramming
Python
Pto rgamn
P no


In [ ]:
text = "!!!Hello, World!!!"

# strip() removes from both sides
trimmed = text.strip('!')
print(trimmed)  # Output: "Hello, World!"

# lstrip() removes only from the left
left_trimmed = text.lstrip()
print(left_trimmed)  # Output: "Hello, World!   "

# rstrip() removes only from the right
right_trimmed = text.rstrip()
print(right_trimmed)  # Output: "   Hello, World!"

text = "@##@#(Hello###!!~"
print(text.strip('@#(~!'))  # Output: "Hello"

Hello, World
!!!Hello, World!!!
!!!Hello, World!!!
Hello


In [ ]:
text = "apple,banana,cherry"
fruits = text.split(",")
print(fruits)  # Output: ['apple', 'banana', 'cherry']

# Splitting with maxsplit (limits the number of splits)
text = "one two three four FIVE"
words = text.split(" ", 3)
print(words)  # Output: ['one', 'two', 'three four']

['apple', 'banana', 'cherry']
['one', 'two', 'three', 'four FIVE']


In [ ]:
text = "one two three four"
words = text.split(" ", 2)
print(words)  # Output: ['one,two', 'three', 'four']

AttributeError: 'str' object has no attribute 'Lsplit'

In [ ]:
words = ("Hello", "World", "Python")
joined = " ".join(words)
print(joined)  # Output: "Hello World Python"

# Joining with a different separator
joined_with_comma = ", ".join(words)
print(joined_with_comma)  # Output: "Hello, World, Python"

# Joining characters of a string
chars = ["1", "2", "ABC"]
joined_chars = "-".join(chars)
print(joined_chars)  # Output: "a-b-c"

Hello World Python
Hello, World, Python
1-2-ABC


In [ ]:
text = "Python PrograPring"

# find() returns -1 if not found
print(text.find("Pr",7, 9))  # Output: 7
print(text.find("Java"))  # Output: -1

# index() raises an error if not found
print(text.index("Pro"))  # Output: 7
print(text.index("Java"))

7
-1
7


ValueError: substring not found

In [ ]:
text = "hello worlld ll"
print(text.count("ll"))  # Output: 3
filename = "document.pdf"
print(filename.endswith("txt"))  # Output: True
print(filename.startswith("doc"))  # Output: True

3
False
True


In [ ]:
text = "Hello, World!"

# Basic replacement
new_text = text.replace("Hello", "Python")
print(new_text)

# Limiting replacements
text = "ha ha ha"
new_text = text.replace("ha", "ho", 2)
print(new_text)  # Output: "ho ho ha"

Python, World!
ho ho ha
